@table([
    'headings'      => ['Name', 'Description', 'Details', 'Link'],
    'showFooter'    => true,
    'filterable'    => true,
    'sortable'      => true,
    'pagination'    => 10,
    'list'          => [
        ['columns' => ['row1', 'hejsan', 'svejsan', 'urlis']],
        ['columns' => ['row2', 'hejsan', 'svejsan', 'urlis']],
        ['columns' => ['row3', 'hejsan', 'svejsan', 'urlis']],
        ['columns' => ['row4', 'hejsan', 'svejsan', 'urlis']],
        ['columns' => ['row5', 'hejsan', 'svejsan', 'urlis']],
        ['columns' => ['row6', 'hejsan', 'svejsan', 'urlis']],
        ['columns' => ['row7', 'hejsan', 'svejsan', 'urlis']],
        ['columns' => ['row8', 'hejsan', 'svejsan', 'urlis']],
        ['columns' => ['row9', 'hejsan', 'svejsan', 'urlis']],
        ['columns' => ['row10', 'hejsan', 'svejsan', 'urlis']],
        ['columns' => ['row11', 'hejsan', 'svejsan', 'urlis']],
        ['columns' => ['row12', 'hejsan', 'svejsan', 'urlis']],
        ['columns' => ['row13', 'hejsan', 'svejsan', 'urlis']],
        ['columns' => ['row112', 'hejsan', 'svejsan', 'urlis']],
        ['columns' => ['row112', 'hejsan', 'svejsan', 'urlis']],
        ['columns' => ['row112', 'hejsan', 'svejsan', 'urlis']],
        ['columns' => ['row112', 'hejsan', 'svejsan', 'urlis']],
        ['columns' => ['row112', 'hejsan', 'svejsan', 'urlis']],
        ['columns' => ['row113', 'hejsan', 'svejsan', 'urlis']],
        ['columns' => ['row113', 'hejsan', 'svejsan', 'urlis']],
        ['columns' => ['row113', 'hejsan', 'svejsan', 'urlis']],
        ['columns' => ['row113', 'hejsan', 'svejsan', 'urlis']],
        ['columns' => ['row113', 'hejsan', 'svejsan', 'urlis']],
    ],
])
@endtable