#!/usr/local/bin/python3

import subprocess
import sys
import os
from git import Repo

def abort_commit_process(msg):
    print ('\n\n\033[5;31;40m')
    print (msg)
    sys.exit(1)

def validate_msg(msg, branch):
    line_number = 0
    at_body = False

    if(branch == 'master'):

        for line in msg:
            line_length = len(line)

            if line_number == 0 and (line_length < 1 or line_length > 73):
                abort_commit_process('Lenght of subject has to be 1 - 50 characters.')
            elif line_number == 0 and line[-1] == '.':
                abort_commit_process('The subject cannot end with period.')
            elif line_number == 1 and len(line) != 1:
                abort_commit_process('Second line has to be empty.')
            elif line_number == 2:
                at_body = True

            if at_body and line_length - 1 > 72:
                abort_commit_process('Wrap each line of the body at 72 characters.')

            line_number += 1

msg_file = open(sys.argv[1], 'r')
msg = msg_file.readlines()
msg_file.close()

repo_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../'))
repo = Repo(repo_path)
branch = repo.active_branch.name

validate_msg(msg,branch)