name: Build and deploy styleguide optimize

on:
  push:
    branches:
    - "build-opmtimize"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15'

    - name: Setup PHP with composer v2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer:v2


    - name: Inject access token in .npmrc.
      run: | 
        # echo "registry=https://npm.pkg.github.com/helsingborg-stad" >> ~/.npmrc
        # echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
        # cat ~/.npmrc
        # node -v

    - name: Execute buildscript.
      run: php ./build.php --cleanup

    - name: Cleanup .npmrc
      run: rm ~/.npmrc
