name: Test

on:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 24.6
        cache: 'npm'
        cache-dependency-path: ./package-lock.json

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer:v2

    - name: Install composer packages
      run: composer i

    - name: Configure npm for GitHub Packages
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
        echo "@helsingborg-stad:registry=https://npm.pkg.github.com" >> .npmrc

    - name: Install npm packages
      run: npm ci

    - name: Install Playwright Chromium
      run: npx playwright install --with-deps chromium

    - name: Run tests (Jest)
      run: npm test

    - name: Run typecheck (TypeScript)
      run: npm run typecheck

    - name: Run Tests (PHPUnit)
      run: composer test

    - name: Build CSS
      run: npm run build

    - name: Run Playwright e2e tests
      run: npm run test:e2e

    - name: Run CSS validation (W3C)
      run: npm run test:css-validator

    - name: Run built JS console validation
      run: npm run test:js-console-validator

    - name: Run CSS linting (Stylelint)
      run: npm run lint:scss